language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"

before_install:
    - travis_retry sudo apt-get -y install libtango7 libtango7-devel;

install:
    - pip install -r requirements.txt
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
    - python setup.py install
    - pip install coveralls


script: nosetests
