language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"

env:
    - LIBTANGO=7
    - LIBTANGO=8

before_install:
    # Travis uses Ubunu 12.04 which comes with Tango 7
    if [[$LIBTANGO == 8]]; then
        - travis_retry sudo add-apt-repository -y ppa:tango-controls/core;
    fi;

    - travis_retry sudo apt-get update -qq;

    if [[$LIBTANGO == 7]]; then
        - travis_retry sudo apt-get -y install libtango7;
        - travis_retry sudo apt-get -y install libtango7-dev;
    fi;
    if [[$LIBTANGO == 8]]; then
        - travis_retry sudo apt-get -y install libtango8;
        - travis_retry sudo apt-get -y install libtango8-dev;
    fi;


install:
    - pip install -r requirements.txt
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
    - python setup.py install
    - pip install coveralls


script: nosetests
