language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"

before_install:

install:
    - travis_retry sudo apt-get -qq -y install python-numpy;
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi

script:
    - python setup.py build
    - nosetests
