language: python
# Here we use anaconda for 2.6 and 3.4, since it provides the simplest
# interface for running different versions of Python. We could also use
# it for 2.7, but the Ubuntu system has installable 2.7 Qt4-GL, which
# allows for more complete testing.
# Size testing can be skipped by adding "[size skip]" within a commit message.
virtualenv:
system_site_packages: true
env:
# Enable python 2 and python 3 builds
# Note that the 2.6 build doesn't get flake8, and runs old versions of
# Pyglet and GLFW to make sure we deal with those correctly
- PYTHON=2.6 DEPS=full TEST=standard # functionality
- PYTHON=2.7 DEPS=full TEST=standard
- PYTHON=2.7 DEPS=minimal TEST=standard
- PYTHON=3.4 DEPS=full TEST=standard
- PYTHON=2.7 DEPS=full TEST=examples # test examples
- PYTHON=3.4 DEPS=full TEST=examples
- PYTHON=3.4 DEPS=minimal TEST=extra # test file sizes, style, line endings
before_install:
- REDIRECT_TO=/dev/stdout # change to /dev/null to silence Travis
travis_retry sudo apt-get -qq -y install libtango;
